import React, { useState } from "react";

const cityOptions = [
  { value: "All", label: "All" },
  { value: "Seoul", label: "Seoul" },
  { value: "Busan", label: "Busan" },
  { value: "Daegu", label: "Daegu" },
  { value: "Incheon", label: "Incheon" },
  { value: "Gwangju", label: "Gwangju" },
  { value: "Daejeon", label: "Daejeon" },
  { value: "Ulsan", label: "Ulsan" },
  { value: "Gyeonggi", label: "Gyeonggi" },
  { value: "Gangwon", label: "Gangwon" },
  { value: "Chungbuk", label: "Chungbuk" },
  { value: "Chungnam", label: "Chungnam" },
  { value: "Jeonbuk", label: "Jeonbuk" },
  { value: "Jeonnam", label: "Jeonnam" },
  { value: "Gyeongbuk", label: "Gyeongbuk" },
  { value: "Gyeongnam", label: "Gyeongnam" },
  { value: "Jeju", label: "Jeju" },
];

const countyOptions = {
  All: ["All"],
  Seoul: [
    "All",
    "Gangnam-gu",
    "Gangdong-gu",
    "Gangbuk-gu",
    "Gangseo-gu",
    "Gwanak-gu",
    "Gwangjin-gu",
    "Guro-gu",
    "Geumcheon-gu",
    "Nowon-gu",
    "Dobong-gu",
    "Dongdaemun-gu",
    "Dongjak-gu",
    "Mapo-gu",
    "Seodaemun-gu",
    "Seocho-gu",
    "Seongdong-gu",
    "Seongbuk-gu",
    "Songpa-gu",
    "Yangcheon-gu",
    "Yeongdeungpo-gu",
    "Yongsan-gu",
    "Eunpyeong-gu",
    "Jongno-gu",
    "Jung-gu",
    "Jungnang-gu",
  ],
  Busan: [
    "All",
    "Gangseo-gu",
    "Geumjeong-gu",
    "Nam-gu",
    "Dong-gu",
    "Dongnae-gu",
    "Busanjin-gu",
    "Buk-gu",
    "Sasang-gu",
    "Saha-gu",
    "Seo-gu",
    "Suyeong-gu",
    "Yeonje-gu",
    "Yeongdo-gu",
    "Jung-gu",
    "Haeundae-gu",
    "Gijang-gun",
  ],
  Daegu: [
    "All",
    "Nam-gu",
    "Dalseo-gu",
    "Dong-gu",
    "Buk-gu",
    "Seo-gu",
    "Suseong-gu",
    "Jung-gu",
    "Dalseong-gun",
  ],
  Incheon: [
    "All",
    "Gyeyang-gu",
    "Nam-gu",
    "Namdong-gu",
    "Dong-gu",
    "Bupyeong-gu",
    "Seo-gu",
    "Yeonsu-gu",
    "Jung-gu",
    "Ganghwa-gun",
    "Ongjin-gun",
  ],
  Gwangju: ["All", "Gwangsan-gu", "Nam-gu", "Dong-gu", "Buk-gu", "Seo-gu"],
  Daejeon: ["All", "Daedeok-gu", "Dong-gu", "Seo-gu", "Yuseong-gu", "Jung-gu"],
  Ulsan: ["All", "Nam-gu", "Dong-gu", "Buk-gu", "Jung-gu", "Ulju-gun"],
  Gyeonggi: [
    "All",
    "Goyang-si",
    "Gwacheon-si",
    "Gwangmyeong-si",
    "Guri-si",
    "Gunpo-si",
    "Namyangju-si",
    "Dongducheon-si",
    "Bucheon-si",
    "Seongnam-si",
    "Suwon-si",
    "Siheung-si",
    "Ansan-si",
    "Anyang-si",
    "Osan-si",
    "Uiwang-si",
    "Uijeongbu-si",
    "Pyeongtaek-si",
    "Hanam-si",
    "Gapyeong-gun",
    "Gwangju-si",
    "Gimpo-si",
    "Anseong-si",
    "Yangju-gun",
    "Yangpyeong-gun",
    "Yeoju-gun",
    "Yeoncheon-gun",
    "Yongin-si",
    "Icheon-gun",
    "Paju-si",
    "Pocheon-si",
    "Hwaseong-si",
  ],
  Gangwon: [
    "All",
    "Gangneung-si",
    "Donghae-si",
    "Samcheok-si",
    "Sokcho-si",
    "Wonju-si",
    "Chuncheon-si",
    "Taebaek-si",
    "Goseong-gun",
    "Yanggu-gun",
    "Yangyang-gun",
    "Yeongwol-gun",
    "Inje-gun",
    "Jeongseon-gun",
    "Cheorwon-gun",
    "Pyeongchang-gun",
    "Hongcheon-gun",
    "Hwacheon-gun",
    "Hwaseong-gun",
  ],
  Chungbuk: [
    "All",
    "Jecheon-si",
    "Cheongju-si",
    "Chungju-si",
    "Goesan-gun",
    "Danyang-gun",
    "Boeun-gun",
    "Yeongdong-gun",
    "Okcheon-gun",
    "Eumseong-gun",
    "Jincheon-gun",
    "Cheongwon-gun",
  ],
  Chungnam: [
    "All",
    "Gongju-si",
    "Boryeong-si",
    "Seosan-si",
    "Asan-si",
    "Cheonan-si",
    "Geumsan-gun",
    "Nonsan-si",
    "Dangjin-si",
    "Buyeo-gun",
    "Seocheon-gun",
    "Yeongi-gun",
    "Yesan-gun",
    "Cheongyang-gun",
    "Taean-gun",
    "Hongseong-gun",
  ],
  Jeonbuk: [
    "All",
    "Gunsan-si",
    "Gimje-si",
    "Namwon-si",
    "Iksan-si",
    "Jeonju-si",
    "Jeongeup-si",
    "Gochang-gun",
    "Muju-gun",
    "Buan-gun",
    "Sunchang-gun",
    "Wanju-gun",
    "Imsil-gun",
    "Jangsu-gun",
    "Jinan-gun",
  ],
  Jeonnam: [
    "All",
    "Gwangyang-si",
    "Naju-si",
    "Mokpo-si",
    "Suncheon-si",
    "Yeosu-si",
    "Yeocheon-si",
    "Gangjin-gun",
    "Goheung-gun",
    "Gokseong-gun",
    "Gurye-gun",
    "Damyang-gun",
    "Muan-gun",
    "Boseong-gun",
    "Shinan-gun",
    "Yeocheon-gun",
    "Yeonggwang-gun",
    "Yeongam-gun",
    "Wando-gun",
    "Jangseong-gun",
    "Jangheung-gun",
    "Jindo-gun",
    "Hampyeong-gun",
    "Haenam-gun",
    "Hwasun-gun",
  ],
  Gyeongbuk: [
    "All",
    "Gyeongsan-si",
    "Gyeongju-si",
    "Gumi-si",
    "Gimcheon-si",
    "Mungyeong-si",
    "Sangju-si",
    "Andong-si",
    "Yeongju-si",
    "Yeongcheon-si",
    "Pohang-si",
    "Goryeong-gun",
    "Gunwi-gun",
    "Bonghwa-gun",
    "Seongju-gun",
    "Yeongdeok-gun",
    "Yeongyang-gun",
    "Yecheon-gun",
    "Ulleung-gun",
    "Uljin-gun",
    "Uiseong-gun",
    "Cheongdo-gun",
    "Cheongsong-gun",
    "Chilgok-gun",
  ],
  Gyeongnam: [
    "All",
    "Geoje-si",
    "Gimhae-si",
    "Masan-si",
    "Miryang-si",
    "Sacheon-si",
    "Ulsan-si",
    "Jinju-si",
    "Jinhae-si",
    "Changwon-si",
    "Tongyeong-si",
    "Geochang-gun",
    "Goseong-gun",
    "Namhae-gun",
    "Sancheong-gun",
    "Yangsan-si",
    "Uiryeong-gun",
    "Changnyeong-gun",
    "Hadong-gun",
    "Haman-gun",
    "Hamyang-gun",
    "Hapcheon-gun",
  ],
  Jeju: ["All", "Seogwipo-si", "Jeju-si", "Namjeju-gun", "Bukjeju-gun"],
};
const JOB = [
  { value: "base", name: "Position" },
  { value: "test", name: "Test" },
];

const OPTIONS = [
  { value: "latest", name: "Latest" },
  { value: "oldest", name: "Oldest" },
  { value: "viewest", name: "Most Viewed" },
];

const Location = () => {
  const [selectedCity, setSelectedCity] = useState("All");
  const [counties, setCounties] = useState(countyOptions["All"]);

  const handleCityChange = (event) => {
    const selectedCity = event.target.value;
    setSelectedCity(selectedCity);
    setCounties(countyOptions[selectedCity]);
  };

  return (
    <form>
      <label>
        City/Province : &nbsp;
        <select value={selectedCity} onChange={handleCityChange}>
          {cityOptions.map((city) => (
            <option key={city.value} value={city.value}>
              {city.label}
            </option>
          ))}
        </select>
      </label>
      <label>
        District/County : &nbsp;
        <select>
          {counties.map((county) => (
            <option key={county} value={county}>
              {county}
            </option>
          ))}
        </select>
      </label>
    </form>
  );
};

export { Location, JOB, OPTIONS };
